spring.application.name=auth-ms
server.port=5001
jwt.secret=ATkMUQvW8mMEloJogcynr60WtthyCdMgdL599dowO7IwTceyb1W8paK5UN0i1JKJpa31vsncpJP

spring.datasource.url=jdbc:postgresql://localhost:5432/authDataBase
spring.datasource.username=postgres
spring.datasource.password=cisco
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true